import{S as v,a as L,i as a}from"./assets/vendor-mj6yH6lW.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const y=document.querySelector(".gallery");function m(s){y.innerHTML=s.map(({webformatURL:t,largeImageURL:o,tags:c,likes:e,views:r,comments:n,downloads:p})=>`
      <li class="gallery-item">
        <a href="${o}" class="gallery-link">
          <img src="${t}" alt="${c}" class="gallery-image" />
        </a>
        <div class="info">
            <p><strong>Likes:</strong> ${e}</p>
            <p><strong>Views:</strong> ${r}</p>
            <p><strong>Comments:</strong> ${n}</p>
            <p><strong>Downloads:</strong> ${p}</p>
          </div>
      </li>`).join(""),y.insertAdjacentHTML("beforeend",markup),b.refresh()}const b=new v(".gallery a",{captionsData:"alt",captionDelay:250}),w="49441888-9a9fca759a65c9c8b8f6579f2",E="https://pixabay.com/api/";async function h(s,t=1){try{const o=await L.get(E,{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return console.log(o.data),o.data.hits}catch(o){throw console.error("Error fetching images:",o),o}}let l=1,d="";const u=15,f=document.querySelector(".form"),g=document.querySelector(".loader"),q=document.querySelector(".gallery"),i=document.querySelector(".load-more");f.addEventListener("submit",async s=>{if(s.preventDefault(),d=s.target.elements["search-text"].value.trim(),!d){a.error({title:"Error",message:"Please enter a search query!"});return}g.classList.remove("visually-hidden"),q.innerHTML="",f.reset(),l=1;try{const{hits:t,totalHits:o}=await h(d,l,u);if(t.length===0){a.warning({title:"Oops!",message:"No images found. Try again!"});return}m(t),i.classList.add("visually-hidden"),l*u>=o&&(i.classlist.remove("visually-hidden"),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Failed to fetch images. Try again later!"})}finally{g.classList.add("visually-hidden")}});i.addEventListener("click",async()=>{l+=1,g.classList.remove("visually-hidden"),i.classList.add("visually-hidden");try{const{hits:s,totalHits:t}=await h(d,l,u);m(s),S(),l*u>=t?(i.classlist.add("visually-hidden"),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):i.classList.remove("visually-hidden")}catch{a.error({title:"Error",message:"Failed to fetch images. Try again later!"})}finally{g.classList.add("visually-hidden")}});function S(){const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
