import{S as f,a as S,i as m}from"./assets/vendor-mj6yH6lW.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();document.querySelector(".gallery");function y(s,r){const o=r.map(({webformatURL:a,largeImageURL:e,tags:t,likes:n,views:v,comments:L,downloads:b})=>`
      <li class="gallery-item">
        <a href="${e}" class="gallery-link">
          <img src="${a}" alt="${t}" class="gallery-image" />
        </a>
        <div class="info">
            <p><strong>Likes:</strong> ${n}</p>
            <p><strong>Views:</strong> ${v}</p>
            <p><strong>Comments:</strong> ${L}</p>
            <p><strong>Downloads:</strong> ${b}</p>
          </div>
      </li>`).join("");s.insertAdjacentHTML("beforeend",o),q.refresh()}const q=new f(".gallery a",{captionsData:"alt",captionDelay:250}),w="49441888-9a9fca759a65c9c8b8f6579f2",P="https://pixabay.com/api/";let E=15;async function p(s,r=1){try{const o=await S.get(P,{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:E}}),{hits:a,totalHits:e}=o.data;return a.length===0?(m.warning({title:"No results!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),{images:[],totalHits:0}):{images:a,totalHits:e}}catch(o){return console.error("Error:",o),{images:[],totalHits:0}}}const H={form:document.querySelector(".form"),input:document.querySelector('[name="search-text"]'),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more")};let c=null,i=1,d=0;const $=15,{form:h,input:M,gallery:g,loader:u,loadMoreBtn:l}=H;h.addEventListener("submit",O);l.addEventListener("click",R);async function O(s){if(s.preventDefault(),i=1,d=0,g.innerHTML="",c=M.value.trim(),c===""){m.error({title:"Error:",message:"Please fill in the search field before submitting!",position:"topRight"});return}u.classList.remove("visually-hidden");try{const{images:r,totalHits:o}=await p(c,i);y(g,r),d=Math.ceil(o/$),d>i&&l.classList.remove("visually-hidden")}catch(r){console.error("Error:",r)}finally{u.classList.add("visually-hidden"),h.reset()}}async function R(){i+=1;try{l.classList.add("visually-hidden"),u.classList.remove("visually-hidden");const{images:s}=await p(c,i);y(g,s),new f(".gallery a").refresh();const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),i>=d?(l.classList.add("visually-hidden"),m.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):l.classList.remove("visually-hidden")}catch(s){console.error("Error:",s)}finally{u.classList.add("visually-hidden")}}
//# sourceMappingURL=index.js.map
